#!/bin/bash
IMAGE_NAME=capitol.jpeg
IMAGE_INFO=$(identify $IMAGE_NAME)
IMAGE_WIDTH=$(echo $IMAGE_INFO | sed "s/.*JPEG \([0-9]*\)x\([0-9]*\).*/\1/")
IMAGE_HEIGHT=$(echo $IMAGE_INFO | sed "s/.*JPEG \([0-9]*\)x\([0-9]*\).*/\2/")
for width in 768 1200 1920; do
	height=$(echo $width*$IMAGE_HEIGHT/$IMAGE_WIDTH | bc)
	geom=${width}x${height}
	echo convert $IMAGE_NAME -resize $geom $(echo $IMAGE_NAME | sed "s/.jpeg/_$geom.jpeg/")
done